
SNSTopicName: CecilTopic
SQSQueueName: CecilQueue
ForeignIAMRoleName: CecilRole
# TODO: add CecilRootUser as a configurable parameter

MailerDomain: sandbox9d136c8312a843a9ac111311c17c5c66.mailgun.org
MailerAPIKey       : key-82ea6cfe7dc69f6cf30890f3789c388c
MailerPublicAPIKey : pubkey-e9ceff19d27498fd8fa0df40e155c554

ServerScheme: http
ServerHostName: "0.0.0.0"
ServerPort: ":8080"

# See https://golang.org/pkg/time/#ParseDuration for examples
LeaseDuration: "72h"
LeaseApprovalTimeoutDuration: "24h"
LeaseFirstWarningBeforeExpiry: "48h"
LeaseSecondWarningBeforeExpiry: "1h"
LeaseMaxPerOwner: 10

TokenDuration: "720h" # TokenDuration sets the duration of a JWT API token

# settings for connecting to a postgres DB
postgres:
  host: db.example.com
  port: 5432
  user: username
  dbname: dbname
  sslmode: disable
  password: password
  maxIdleConns: 100
  maxOpenConns: 100
  debug: true
