
SNSTopicName: ZeroCloudTopic
SQSQueueName: ZeroCloudQueue
ForeignIAMRoleName: ZeroCloudRole

MailerDomain: sandbox9d136c8312a843a9ac111311c17c5c66.mailgun.org
MailerAPIKey       : key-82ea6cfe7dc69f6cf30890f3789c388c
MailerPublicAPIKey : pubkey-e9ceff19d27498fd8fa0df40e155c554

ServerScheme: http
ServerHostName: "0.0.0.0"
ServerPort: ":8080"

# See https://golang.org/pkg/time/#ParseDuration for examples
LeaseDuration: "72h"
LeaseApprovalTimeoutDuration: "12h"
LeaseForewarningBeforeExpiry: "24h"
LeaseMaxPerOwner: 2

demo:
  Email:          "slv.balsan@gmail.com"
  Provider:       "aws"
  AWSID:          "859795398601"
  ExternalID:     "hithere"
  SecondaryEmail: "slavomir.balsan@gmail.com"

demo1:
  Email:          "traun.leyden@gmail.com"
  Provider:       "aws"
  AWSID:          "788612350743"
  ExternalID:     "bigdb_zerocloud"
  SecondaryEmail: "tleyden@yahoo.com"
