// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "Cecil": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/tleyden/cecil/design
// --out=$(GOPATH)/src/github.com/tleyden/cecil/goa
// --version=v1.0.0

package app
