// Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements;
// and to You under the Apache License, Version 2.0.  See LICENSE in project root for full license + copyright.

// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "Cecil": CLI Commands
//
// Command:
// $ goagen
// --design=github.com/tleyden/cecil/design
// --out=$(GOPATH)/src/github.com/tleyden/cecil/goa
// --version=v1.0.0

package cli

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/goadesign/goa"
	goaclient "github.com/goadesign/goa/client"
	uuid "github.com/goadesign/goa/uuid"
	"github.com/spf13/cobra"
	"github.com/tleyden/cecil/goa/client"
	"log"
	"net/url"
	"os"
	"strconv"
	"strings"
	"time"
)

type (
	// CreateAccountCommand is the command line data structure for the create action of account
	CreateAccountCommand struct {
		Payload     string
		ContentType string
		PrettyPrint bool
	}

	// MailerConfigAccountCommand is the command line data structure for the mailerConfig action of account
	MailerConfigAccountCommand struct {
		Payload     string
		ContentType string
		// Account ID
		AccountID   int
		PrettyPrint bool
	}

	// NewAPITokenAccountCommand is the command line data structure for the new_api_token action of account
	NewAPITokenAccountCommand struct {
		Payload     string
		ContentType string
		// Account ID
		AccountID   int
		PrettyPrint bool
	}

	// RemoveMailerAccountCommand is the command line data structure for the removeMailer action of account
	RemoveMailerAccountCommand struct {
		// Account ID
		AccountID   int
		PrettyPrint bool
	}

	// RemoveSlackAccountCommand is the command line data structure for the removeSlack action of account
	RemoveSlackAccountCommand struct {
		// Account ID
		AccountID   int
		PrettyPrint bool
	}

	// ShowAccountCommand is the command line data structure for the show action of account
	ShowAccountCommand struct {
		// Account ID
		AccountID   int
		PrettyPrint bool
	}

	// SlackConfigAccountCommand is the command line data structure for the slackConfig action of account
	SlackConfigAccountCommand struct {
		Payload     string
		ContentType string
		// Account ID
		AccountID   int
		PrettyPrint bool
	}

	// VerifyAccountCommand is the command line data structure for the verify action of account
	VerifyAccountCommand struct {
		Payload     string
		ContentType string
		// Account ID
		AccountID   int
		PrettyPrint bool
	}

	// AddCloudaccountCommand is the command line data structure for the add action of cloudaccount
	AddCloudaccountCommand struct {
		Payload     string
		ContentType string
		// Account ID
		AccountID   int
		PrettyPrint bool
	}

	// AddWhitelistedOwnerCloudaccountCommand is the command line data structure for the addWhitelistedOwner action of cloudaccount
	AddWhitelistedOwnerCloudaccountCommand struct {
		Payload     string
		ContentType string
		// Account ID
		AccountID int
		// Cloudaccount ID
		CloudaccountID int
		PrettyPrint    bool
	}

	// DeleteWhitelistedOwnerCloudaccountCommand is the command line data structure for the deleteWhitelistedOwner action of cloudaccount
	DeleteWhitelistedOwnerCloudaccountCommand struct {
		Payload     string
		ContentType string
		// Account ID
		AccountID int
		// Cloudaccount ID
		CloudaccountID int
		PrettyPrint    bool
	}

	// DownloadInitialSetupTemplateCloudaccountCommand is the command line data structure for the downloadInitialSetupTemplate action of cloudaccount
	DownloadInitialSetupTemplateCloudaccountCommand struct {
		// Account ID
		AccountID int
		// Cloudaccount ID
		CloudaccountID int
		PrettyPrint    bool
	}

	// DownloadRegionSetupTemplateCloudaccountCommand is the command line data structure for the downloadRegionSetupTemplate action of cloudaccount
	DownloadRegionSetupTemplateCloudaccountCommand struct {
		// Account ID
		AccountID int
		// Cloudaccount ID
		CloudaccountID int
		PrettyPrint    bool
	}

	// ListRegionsCloudaccountCommand is the command line data structure for the listRegions action of cloudaccount
	ListRegionsCloudaccountCommand struct {
		// Account ID
		AccountID int
		// Cloudaccount ID
		CloudaccountID int
		PrettyPrint    bool
	}

	// ListWhitelistedOwnersCloudaccountCommand is the command line data structure for the listWhitelistedOwners action of cloudaccount
	ListWhitelistedOwnersCloudaccountCommand struct {
		// Account ID
		AccountID int
		// Cloudaccount ID
		CloudaccountID int
		PrettyPrint    bool
	}

	// ShowCloudaccountCommand is the command line data structure for the show action of cloudaccount
	ShowCloudaccountCommand struct {
		// Account ID
		AccountID int
		// Cloudaccount ID
		CloudaccountID int
		PrettyPrint    bool
	}

	// SubscribeSNSToSQSCloudaccountCommand is the command line data structure for the subscribeSNSToSQS action of cloudaccount
	SubscribeSNSToSQSCloudaccountCommand struct {
		Payload     string
		ContentType string
		// Account ID
		AccountID int
		// Cloudaccount ID
		CloudaccountID int
		PrettyPrint    bool
	}

	// UpdateCloudaccountCommand is the command line data structure for the update action of cloudaccount
	UpdateCloudaccountCommand struct {
		Payload     string
		ContentType string
		// Account ID
		AccountID int
		// Cloudaccount ID
		CloudaccountID int
		PrettyPrint    bool
	}

	// UpdateWhitelistedOwnerCloudaccountCommand is the command line data structure for the updateWhitelistedOwner action of cloudaccount
	UpdateWhitelistedOwnerCloudaccountCommand struct {
		Payload     string
		ContentType string
		// Account ID
		AccountID int
		// Cloudaccount ID
		CloudaccountID int
		PrettyPrint    bool
	}

	// ActionsEmailActionCommand is the command line data structure for the actions action of email_action
	ActionsEmailActionCommand struct {
		// Action to be peformed on the lease
		Action string
		// Hash of group UID
		GroupUIDHash string
		// UUID of the lease
		LeaseUUID string
		// The signature of this link
		Sig string
		// The token_once of this link
		Tok         string
		PrettyPrint bool
	}

	// DeleteFromDBLeasesCommand is the command line data structure for the deleteFromDB action of leases
	DeleteFromDBLeasesCommand struct {
		// Account ID
		AccountID int
		// Cloudaccount ID
		CloudaccountID int
		// Lease ID
		LeaseID     int
		PrettyPrint bool
	}

	// ListLeasesForAccountLeasesCommand is the command line data structure for the listLeasesForAccount action of leases
	ListLeasesForAccountLeasesCommand struct {
		// Account ID
		AccountID   int
		Terminated  string
		PrettyPrint bool
	}

	// ListLeasesForCloudaccountLeasesCommand is the command line data structure for the listLeasesForCloudaccount action of leases
	ListLeasesForCloudaccountLeasesCommand struct {
		// Account ID
		AccountID int
		// Cloudaccount ID
		CloudaccountID int
		Terminated     string
		PrettyPrint    bool
	}

	// SetExpiryLeasesCommand is the command line data structure for the setExpiry action of leases
	SetExpiryLeasesCommand struct {
		// Account ID
		AccountID int
		// Cloudaccount ID
		CloudaccountID int
		// Lease ID
		LeaseID int
		// Target expiry datetime
		ExpiresAt   string
		PrettyPrint bool
	}

	// ShowLeasesCommand is the command line data structure for the show action of leases
	ShowLeasesCommand struct {
		// Account ID
		AccountID int
		// Cloudaccount ID
		CloudaccountID int
		// Lease ID
		LeaseID     int
		PrettyPrint bool
	}

	// TerminateLeasesCommand is the command line data structure for the terminate action of leases
	TerminateLeasesCommand struct {
		// Account ID
		AccountID int
		// Cloudaccount ID
		CloudaccountID int
		// Lease ID
		LeaseID     int
		PrettyPrint bool
	}

	// OrderInstancesReportReportCommand is the command line data structure for the orderInstancesReport action of report
	OrderInstancesReportReportCommand struct {
		Payload     string
		ContentType string
		// Account ID
		AccountID int
		// Cloudaccount ID
		CloudaccountID int
		PrettyPrint    bool
	}

	// ShowReportReportCommand is the command line data structure for the showReport action of report
	ShowReportReportCommand struct {
		// Account ID
		AccountID int
		// Cloudaccount ID
		CloudaccountID int
		// Report UUID
		ReportUUID  string
		PrettyPrint bool
	}

	// ShowRootCommand is the command line data structure for the show action of root
	ShowRootCommand struct {
		PrettyPrint bool
	}

	// DownloadCommand is the command line data structure for the download command.
	DownloadCommand struct {
		// OutFile is the path to the download output file.
		OutFile string
	}
)

// RegisterCommands registers the resource action CLI commands.
func RegisterCommands(app *cobra.Command, c *client.Client) {
	var command, sub *cobra.Command
	command = &cobra.Command{
		Use:   "actions",
		Short: `Perform an action on a lease`,
	}
	tmp1 := new(ActionsEmailActionCommand)
	sub = &cobra.Command{
		Use:   `email-action ["/email_action/leases/LEASE_UUID/GROUP_UID_HASH/ACTION"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp1.Run(c, args) },
	}
	tmp1.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp1.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "add",
		Short: `Add new cloudaccount`,
	}
	tmp2 := new(AddCloudaccountCommand)
	sub = &cobra.Command{
		Use:   `cloudaccount ["/accounts/ACCOUNT_ID/cloudaccounts"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp2.Run(c, args) },
	}
	tmp2.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp2.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "add-whitelisted-owner",
		Short: `Add new email (plus optional KeyName) to owner tag whitelist`,
	}
	tmp3 := new(AddWhitelistedOwnerCloudaccountCommand)
	sub = &cobra.Command{
		Use:   `cloudaccount ["/accounts/ACCOUNT_ID/cloudaccounts/CLOUDACCOUNT_ID/owners"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp3.Run(c, args) },
	}
	tmp3.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp3.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "create",
		Short: `Create new account`,
	}
	tmp4 := new(CreateAccountCommand)
	sub = &cobra.Command{
		Use:   `account ["/accounts"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp4.Run(c, args) },
	}
	tmp4.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp4.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "delete-fromdb",
		Short: `Delete a lease from DB`,
	}
	tmp5 := new(DeleteFromDBLeasesCommand)
	sub = &cobra.Command{
		Use:   `leases [("/accounts/ACCOUNT_ID/cloudaccounts/CLOUDACCOUNT_ID/leases/LEASE_ID/delete"|"/accounts/ACCOUNT_ID/leases/LEASE_ID/delete")]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp5.Run(c, args) },
	}
	tmp5.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp5.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "delete-whitelisted-owner",
		Short: `Delete a whitelisted owner`,
	}
	tmp6 := new(DeleteWhitelistedOwnerCloudaccountCommand)
	sub = &cobra.Command{
		Use:   `cloudaccount ["/accounts/ACCOUNT_ID/cloudaccounts/CLOUDACCOUNT_ID/owners"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp6.Run(c, args) },
	}
	tmp6.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp6.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "download-initial-setup-template",
		Short: `Download AWS initial setup cloudformation template`,
	}
	tmp7 := new(DownloadInitialSetupTemplateCloudaccountCommand)
	sub = &cobra.Command{
		Use:   `cloudaccount ["/accounts/ACCOUNT_ID/cloudaccounts/CLOUDACCOUNT_ID/tenant-aws-initial-setup.template"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp7.Run(c, args) },
	}
	tmp7.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp7.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "download-region-setup-template",
		Short: `Download AWS region setup cloudformation template`,
	}
	tmp8 := new(DownloadRegionSetupTemplateCloudaccountCommand)
	sub = &cobra.Command{
		Use:   `cloudaccount ["/accounts/ACCOUNT_ID/cloudaccounts/CLOUDACCOUNT_ID/tenant-aws-region-setup.template"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp8.Run(c, args) },
	}
	tmp8.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp8.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "list-leases-for-account",
		Short: `List all leases for account`,
	}
	tmp9 := new(ListLeasesForAccountLeasesCommand)
	sub = &cobra.Command{
		Use:   `leases ["/accounts/ACCOUNT_ID/leases"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp9.Run(c, args) },
	}
	tmp9.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp9.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "list-leases-for-cloudaccount",
		Short: `List all leases for a Cloudaccount`,
	}
	tmp10 := new(ListLeasesForCloudaccountLeasesCommand)
	sub = &cobra.Command{
		Use:   `leases ["/accounts/ACCOUNT_ID/cloudaccounts/CLOUDACCOUNT_ID/leases"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp10.Run(c, args) },
	}
	tmp10.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp10.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "list-regions",
		Short: `List all regions and their status`,
	}
	tmp11 := new(ListRegionsCloudaccountCommand)
	sub = &cobra.Command{
		Use:   `cloudaccount ["/accounts/ACCOUNT_ID/cloudaccounts/CLOUDACCOUNT_ID/regions"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp11.Run(c, args) },
	}
	tmp11.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp11.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "list-whitelisted-owners",
		Short: `List whitelisted owners`,
	}
	tmp12 := new(ListWhitelistedOwnersCloudaccountCommand)
	sub = &cobra.Command{
		Use:   `cloudaccount ["/accounts/ACCOUNT_ID/cloudaccounts/CLOUDACCOUNT_ID/owners"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp12.Run(c, args) },
	}
	tmp12.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp12.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "mailer-config",
		Short: `Configure custom mailer`,
	}
	tmp13 := new(MailerConfigAccountCommand)
	sub = &cobra.Command{
		Use:   `account ["/accounts/ACCOUNT_ID/mailer_config"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp13.Run(c, args) },
	}
	tmp13.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp13.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "newapi-token",
		Short: `Create new API token`,
	}
	tmp14 := new(NewAPITokenAccountCommand)
	sub = &cobra.Command{
		Use:   `account ["/accounts/ACCOUNT_ID/new_api_token"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp14.Run(c, args) },
	}
	tmp14.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp14.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "order-instances-report",
		Short: `Order the creation of a report about instances`,
	}
	tmp15 := new(OrderInstancesReportReportCommand)
	sub = &cobra.Command{
		Use:   `report ["/accounts/ACCOUNT_ID/cloudaccounts/CLOUDACCOUNT_ID/reports/instances"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp15.Run(c, args) },
	}
	tmp15.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp15.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "remove-mailer",
		Short: `Remove custom mailer`,
	}
	tmp16 := new(RemoveMailerAccountCommand)
	sub = &cobra.Command{
		Use:   `account ["/accounts/ACCOUNT_ID/mailer_config"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp16.Run(c, args) },
	}
	tmp16.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp16.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "remove-slack",
		Short: `Remove slack`,
	}
	tmp17 := new(RemoveSlackAccountCommand)
	sub = &cobra.Command{
		Use:   `account ["/accounts/ACCOUNT_ID/slack_config"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp17.Run(c, args) },
	}
	tmp17.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp17.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "set-expiry",
		Short: `Set expiry of a lease`,
	}
	tmp18 := new(SetExpiryLeasesCommand)
	sub = &cobra.Command{
		Use:   `leases [("/accounts/ACCOUNT_ID/cloudaccounts/CLOUDACCOUNT_ID/leases/LEASE_ID/expiry"|"/accounts/ACCOUNT_ID/leases/LEASE_ID/expiry")]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp18.Run(c, args) },
	}
	tmp18.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp18.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "show",
		Short: `show action`,
	}
	tmp19 := new(ShowAccountCommand)
	sub = &cobra.Command{
		Use:   `account ["/accounts/ACCOUNT_ID"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp19.Run(c, args) },
	}
	tmp19.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp19.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	tmp20 := new(ShowCloudaccountCommand)
	sub = &cobra.Command{
		Use:   `cloudaccount ["/accounts/ACCOUNT_ID/cloudaccounts/CLOUDACCOUNT_ID"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp20.Run(c, args) },
	}
	tmp20.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp20.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	tmp21 := new(ShowLeasesCommand)
	sub = &cobra.Command{
		Use:   `leases [("/accounts/ACCOUNT_ID/cloudaccounts/CLOUDACCOUNT_ID/leases/LEASE_ID"|"/accounts/ACCOUNT_ID/leases/LEASE_ID")]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp21.Run(c, args) },
	}
	tmp21.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp21.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	tmp22 := new(ShowRootCommand)
	sub = &cobra.Command{
		Use:   `root ["/"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp22.Run(c, args) },
	}
	tmp22.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp22.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "show-report",
		Short: `Show a single report`,
	}
	tmp23 := new(ShowReportReportCommand)
	sub = &cobra.Command{
		Use:   `report ["/accounts/ACCOUNT_ID/cloudaccounts/CLOUDACCOUNT_ID/reports/generated/REPORT_UUID"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp23.Run(c, args) },
	}
	tmp23.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp23.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "slack-config",
		Short: `Configure slack`,
	}
	tmp24 := new(SlackConfigAccountCommand)
	sub = &cobra.Command{
		Use:   `account ["/accounts/ACCOUNT_ID/slack_config"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp24.Run(c, args) },
	}
	tmp24.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp24.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "subscribesns-tosqs",
		Short: `Subscribe SNS to SQS`,
	}
	tmp25 := new(SubscribeSNSToSQSCloudaccountCommand)
	sub = &cobra.Command{
		Use:   `cloudaccount ["/accounts/ACCOUNT_ID/cloudaccounts/CLOUDACCOUNT_ID/subscribe-sns-to-sqs"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp25.Run(c, args) },
	}
	tmp25.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp25.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "terminate",
		Short: `Terminate a lease`,
	}
	tmp26 := new(TerminateLeasesCommand)
	sub = &cobra.Command{
		Use:   `leases [("/accounts/ACCOUNT_ID/cloudaccounts/CLOUDACCOUNT_ID/leases/LEASE_ID/terminate"|"/accounts/ACCOUNT_ID/leases/LEASE_ID/terminate")]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp26.Run(c, args) },
	}
	tmp26.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp26.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "update",
		Short: `Update a cloudaccount`,
	}
	tmp27 := new(UpdateCloudaccountCommand)
	sub = &cobra.Command{
		Use:   `cloudaccount ["/accounts/ACCOUNT_ID/cloudaccounts/CLOUDACCOUNT_ID"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp27.Run(c, args) },
	}
	tmp27.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp27.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "update-whitelisted-owner",
		Short: `Modify a whitelisted owner`,
	}
	tmp28 := new(UpdateWhitelistedOwnerCloudaccountCommand)
	sub = &cobra.Command{
		Use:   `cloudaccount ["/accounts/ACCOUNT_ID/cloudaccounts/CLOUDACCOUNT_ID/owners"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp28.Run(c, args) },
	}
	tmp28.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp28.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "verify",
		Short: `Verify account and get API token`,
	}
	tmp29 := new(VerifyAccountCommand)
	sub = &cobra.Command{
		Use:   `account ["/accounts/ACCOUNT_ID/api_token"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp29.Run(c, args) },
	}
	tmp29.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp29.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)

	dl := new(DownloadCommand)
	dlc := &cobra.Command{
		Use:   "download [PATH]",
		Short: "Download file with given path",
		RunE: func(cmd *cobra.Command, args []string) error {
			return dl.Run(c, args)
		},
	}
	dlc.Flags().StringVar(&dl.OutFile, "out", "", "Output file")
	app.AddCommand(dlc)
}

func intFlagVal(name string, parsed int) *int {
	if hasFlag(name) {
		return &parsed
	}
	return nil
}

func float64FlagVal(name string, parsed float64) *float64 {
	if hasFlag(name) {
		return &parsed
	}
	return nil
}

func boolFlagVal(name string, parsed bool) *bool {
	if hasFlag(name) {
		return &parsed
	}
	return nil
}

func stringFlagVal(name string, parsed string) *string {
	if hasFlag(name) {
		return &parsed
	}
	return nil
}

func hasFlag(name string) bool {
	for _, arg := range os.Args[1:] {
		if strings.HasPrefix(arg, "--"+name) {
			return true
		}
	}
	return false
}

func jsonVal(val string) (*interface{}, error) {
	var t interface{}
	err := json.Unmarshal([]byte(val), &t)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func jsonArray(ins []string) ([]interface{}, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []interface{}
	for _, id := range ins {
		val, err := jsonVal(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, val)
	}
	return vals, nil
}

func timeVal(val string) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339, val)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func timeArray(ins []string) ([]time.Time, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []time.Time
	for _, id := range ins {
		val, err := timeVal(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, *val)
	}
	return vals, nil
}

func uuidVal(val string) (*uuid.UUID, error) {
	t, err := uuid.FromString(val)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func uuidArray(ins []string) ([]uuid.UUID, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []uuid.UUID
	for _, id := range ins {
		val, err := uuidVal(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, *val)
	}
	return vals, nil
}

func float64Val(val string) (*float64, error) {
	t, err := strconv.ParseFloat(val, 64)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func float64Array(ins []string) ([]float64, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []float64
	for _, id := range ins {
		val, err := float64Val(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, *val)
	}
	return vals, nil
}

func boolVal(val string) (*bool, error) {
	t, err := strconv.ParseBool(val)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func boolArray(ins []string) ([]bool, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []bool
	for _, id := range ins {
		val, err := boolVal(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, *val)
	}
	return vals, nil
}

// Run downloads files with given paths.
func (cmd *DownloadCommand) Run(c *client.Client, args []string) error {
	var (
		fnf func(context.Context, string) (int64, error)
		fnd func(context.Context, string, string) (int64, error)

		rpath   = args[0]
		outfile = cmd.OutFile
		logger  = goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
		ctx     = goa.WithLogger(context.Background(), logger)
		err     error
	)

	if rpath[0] != '/' {
		rpath = "/" + rpath
	}
	if rpath == "/swagger.json" {
		fnf = c.DownloadSwaggerJSON
		if outfile == "" {
			outfile = "swagger.json"
		}
		goto found
	}
	return fmt.Errorf("don't know how to download %s", rpath)
found:
	ctx = goa.WithLogContext(ctx, "file", outfile)
	if fnf != nil {
		_, err = fnf(ctx, outfile)
	} else {
		_, err = fnd(ctx, rpath, outfile)
	}
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	return nil
}

// Run makes the HTTP request corresponding to the CreateAccountCommand command.
func (cmd *CreateAccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/accounts"
	}
	var payload client.CreateAccountPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.CreateAccount(ctx, path, &payload)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *CreateAccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
}

// Run makes the HTTP request corresponding to the MailerConfigAccountCommand command.
func (cmd *MailerConfigAccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/mailer_config", cmd.AccountID)
	}
	var payload client.MailerConfigAccountPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.MailerConfigAccount(ctx, path, &payload)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *MailerConfigAccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
}

// Run makes the HTTP request corresponding to the NewAPITokenAccountCommand command.
func (cmd *NewAPITokenAccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/new_api_token", cmd.AccountID)
	}
	var payload client.NewAPITokenAccountPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.NewAPITokenAccount(ctx, path, &payload)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *NewAPITokenAccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
}

// Run makes the HTTP request corresponding to the RemoveMailerAccountCommand command.
func (cmd *RemoveMailerAccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/mailer_config", cmd.AccountID)
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.RemoveMailerAccount(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *RemoveMailerAccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
}

// Run makes the HTTP request corresponding to the RemoveSlackAccountCommand command.
func (cmd *RemoveSlackAccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/slack_config", cmd.AccountID)
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.RemoveSlackAccount(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *RemoveSlackAccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
}

// Run makes the HTTP request corresponding to the ShowAccountCommand command.
func (cmd *ShowAccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v", cmd.AccountID)
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ShowAccount(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ShowAccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
}

// Run makes the HTTP request corresponding to the SlackConfigAccountCommand command.
func (cmd *SlackConfigAccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/slack_config", cmd.AccountID)
	}
	var payload client.SlackConfigAccountPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.SlackConfigAccount(ctx, path, &payload)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *SlackConfigAccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
}

// Run makes the HTTP request corresponding to the VerifyAccountCommand command.
func (cmd *VerifyAccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/api_token", cmd.AccountID)
	}
	var payload client.VerifyAccountPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.VerifyAccount(ctx, path, &payload)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *VerifyAccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
}

// Run makes the HTTP request corresponding to the AddCloudaccountCommand command.
func (cmd *AddCloudaccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/cloudaccounts", cmd.AccountID)
	}
	var payload client.AddCloudaccountPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.AddCloudaccount(ctx, path, &payload)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *AddCloudaccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
}

// Run makes the HTTP request corresponding to the AddWhitelistedOwnerCloudaccountCommand command.
func (cmd *AddWhitelistedOwnerCloudaccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/cloudaccounts/%v/owners", cmd.AccountID, cmd.CloudaccountID)
	}
	var payload client.AddWhitelistedOwnerCloudaccountPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.AddWhitelistedOwnerCloudaccount(ctx, path, &payload)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *AddWhitelistedOwnerCloudaccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
	var cloudaccountID int
	cc.Flags().IntVar(&cmd.CloudaccountID, "cloudaccount_id", cloudaccountID, `Cloudaccount ID`)
}

// Run makes the HTTP request corresponding to the DeleteWhitelistedOwnerCloudaccountCommand command.
func (cmd *DeleteWhitelistedOwnerCloudaccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/cloudaccounts/%v/owners", cmd.AccountID, cmd.CloudaccountID)
	}
	var payload client.DeleteWhitelistedOwnerCloudaccountPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.DeleteWhitelistedOwnerCloudaccount(ctx, path, &payload)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *DeleteWhitelistedOwnerCloudaccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
	var cloudaccountID int
	cc.Flags().IntVar(&cmd.CloudaccountID, "cloudaccount_id", cloudaccountID, `Cloudaccount ID`)
}

// Run makes the HTTP request corresponding to the DownloadInitialSetupTemplateCloudaccountCommand command.
func (cmd *DownloadInitialSetupTemplateCloudaccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/cloudaccounts/%v/tenant-aws-initial-setup.template", cmd.AccountID, cmd.CloudaccountID)
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.DownloadInitialSetupTemplateCloudaccount(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *DownloadInitialSetupTemplateCloudaccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
	var cloudaccountID int
	cc.Flags().IntVar(&cmd.CloudaccountID, "cloudaccount_id", cloudaccountID, `Cloudaccount ID`)
}

// Run makes the HTTP request corresponding to the DownloadRegionSetupTemplateCloudaccountCommand command.
func (cmd *DownloadRegionSetupTemplateCloudaccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/cloudaccounts/%v/tenant-aws-region-setup.template", cmd.AccountID, cmd.CloudaccountID)
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.DownloadRegionSetupTemplateCloudaccount(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *DownloadRegionSetupTemplateCloudaccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
	var cloudaccountID int
	cc.Flags().IntVar(&cmd.CloudaccountID, "cloudaccount_id", cloudaccountID, `Cloudaccount ID`)
}

// Run makes the HTTP request corresponding to the ListRegionsCloudaccountCommand command.
func (cmd *ListRegionsCloudaccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/cloudaccounts/%v/regions", cmd.AccountID, cmd.CloudaccountID)
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ListRegionsCloudaccount(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ListRegionsCloudaccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
	var cloudaccountID int
	cc.Flags().IntVar(&cmd.CloudaccountID, "cloudaccount_id", cloudaccountID, `Cloudaccount ID`)
}

// Run makes the HTTP request corresponding to the ListWhitelistedOwnersCloudaccountCommand command.
func (cmd *ListWhitelistedOwnersCloudaccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/cloudaccounts/%v/owners", cmd.AccountID, cmd.CloudaccountID)
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ListWhitelistedOwnersCloudaccount(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ListWhitelistedOwnersCloudaccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
	var cloudaccountID int
	cc.Flags().IntVar(&cmd.CloudaccountID, "cloudaccount_id", cloudaccountID, `Cloudaccount ID`)
}

// Run makes the HTTP request corresponding to the ShowCloudaccountCommand command.
func (cmd *ShowCloudaccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/cloudaccounts/%v", cmd.AccountID, cmd.CloudaccountID)
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ShowCloudaccount(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ShowCloudaccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
	var cloudaccountID int
	cc.Flags().IntVar(&cmd.CloudaccountID, "cloudaccount_id", cloudaccountID, `Cloudaccount ID`)
}

// Run makes the HTTP request corresponding to the SubscribeSNSToSQSCloudaccountCommand command.
func (cmd *SubscribeSNSToSQSCloudaccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/cloudaccounts/%v/subscribe-sns-to-sqs", cmd.AccountID, cmd.CloudaccountID)
	}
	var payload client.SubscribeSNSToSQSCloudaccountPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.SubscribeSNSToSQSCloudaccount(ctx, path, &payload)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *SubscribeSNSToSQSCloudaccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
	var cloudaccountID int
	cc.Flags().IntVar(&cmd.CloudaccountID, "cloudaccount_id", cloudaccountID, `Cloudaccount ID`)
}

// Run makes the HTTP request corresponding to the UpdateCloudaccountCommand command.
func (cmd *UpdateCloudaccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/cloudaccounts/%v", cmd.AccountID, cmd.CloudaccountID)
	}
	var payload client.UpdateCloudaccountPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.UpdateCloudaccount(ctx, path, &payload)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *UpdateCloudaccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
	var cloudaccountID int
	cc.Flags().IntVar(&cmd.CloudaccountID, "cloudaccount_id", cloudaccountID, `Cloudaccount ID`)
}

// Run makes the HTTP request corresponding to the UpdateWhitelistedOwnerCloudaccountCommand command.
func (cmd *UpdateWhitelistedOwnerCloudaccountCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/cloudaccounts/%v/owners", cmd.AccountID, cmd.CloudaccountID)
	}
	var payload client.UpdateWhitelistedOwnerCloudaccountPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.UpdateWhitelistedOwnerCloudaccount(ctx, path, &payload)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *UpdateWhitelistedOwnerCloudaccountCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
	var cloudaccountID int
	cc.Flags().IntVar(&cmd.CloudaccountID, "cloudaccount_id", cloudaccountID, `Cloudaccount ID`)
}

// Run makes the HTTP request corresponding to the ActionsEmailActionCommand command.
func (cmd *ActionsEmailActionCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/email_action/leases/%v/%v/%v", cmd.LeaseUUID, url.QueryEscape(cmd.GroupUIDHash), url.QueryEscape(cmd.Action))
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ActionsEmailAction(ctx, path, cmd.Sig, cmd.Tok)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ActionsEmailActionCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var action string
	cc.Flags().StringVar(&cmd.Action, "action", action, `Action to be peformed on the lease`)
	var groupUIDHash string
	cc.Flags().StringVar(&cmd.GroupUIDHash, "group_uid_hash", groupUIDHash, `Hash of group UID`)
	var leaseUUID string
	cc.Flags().StringVar(&cmd.LeaseUUID, "lease_uuid", leaseUUID, `UUID of the lease`)
	var sig string
	cc.Flags().StringVar(&cmd.Sig, "sig", sig, `The signature of this link`)
	var tok string
	cc.Flags().StringVar(&cmd.Tok, "tok", tok, `The token_once of this link`)
}

// Run makes the HTTP request corresponding to the DeleteFromDBLeasesCommand command.
func (cmd *DeleteFromDBLeasesCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/cloudaccounts/%v/leases/%v/delete", cmd.AccountID, cmd.CloudaccountID, cmd.LeaseID)
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.DeleteFromDBLeases(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *DeleteFromDBLeasesCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
	var cloudaccountID int
	cc.Flags().IntVar(&cmd.CloudaccountID, "cloudaccount_id", cloudaccountID, `Cloudaccount ID`)
	var leaseID int
	cc.Flags().IntVar(&cmd.LeaseID, "lease_id", leaseID, `Lease ID`)
}

// Run makes the HTTP request corresponding to the ListLeasesForAccountLeasesCommand command.
func (cmd *ListLeasesForAccountLeasesCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/leases", cmd.AccountID)
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	var tmp30 *bool
	if cmd.Terminated != "" {
		var err error
		tmp30, err = boolVal(cmd.Terminated)
		if err != nil {
			goa.LogError(ctx, "failed to parse flag into *bool value", "flag", "--terminated", "err", err)
			return err
		}
	}
	resp, err := c.ListLeasesForAccountLeases(ctx, path, tmp30)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ListLeasesForAccountLeasesCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
	var terminated string
	cc.Flags().StringVar(&cmd.Terminated, "terminated", terminated, ``)
}

// Run makes the HTTP request corresponding to the ListLeasesForCloudaccountLeasesCommand command.
func (cmd *ListLeasesForCloudaccountLeasesCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/cloudaccounts/%v/leases", cmd.AccountID, cmd.CloudaccountID)
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	var tmp31 *bool
	if cmd.Terminated != "" {
		var err error
		tmp31, err = boolVal(cmd.Terminated)
		if err != nil {
			goa.LogError(ctx, "failed to parse flag into *bool value", "flag", "--terminated", "err", err)
			return err
		}
	}
	resp, err := c.ListLeasesForCloudaccountLeases(ctx, path, tmp31)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ListLeasesForCloudaccountLeasesCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
	var cloudaccountID int
	cc.Flags().IntVar(&cmd.CloudaccountID, "cloudaccount_id", cloudaccountID, `Cloudaccount ID`)
	var terminated string
	cc.Flags().StringVar(&cmd.Terminated, "terminated", terminated, ``)
}

// Run makes the HTTP request corresponding to the SetExpiryLeasesCommand command.
func (cmd *SetExpiryLeasesCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/cloudaccounts/%v/leases/%v/expiry", cmd.AccountID, cmd.CloudaccountID, cmd.LeaseID)
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	var tmp32 *time.Time
	if cmd.ExpiresAt != "" {
		var err error
		tmp32, err = timeVal(cmd.ExpiresAt)
		if err != nil {
			goa.LogError(ctx, "failed to parse flag into *time.Time value", "flag", "--expires_at", "err", err)
			return err
		}
	}
	if tmp32 == nil {
		goa.LogError(ctx, "required flag is missing", "flag", "--expires_at")
		return fmt.Errorf("required flag expires_at is missing")
	}
	resp, err := c.SetExpiryLeases(ctx, path, *tmp32)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *SetExpiryLeasesCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
	var cloudaccountID int
	cc.Flags().IntVar(&cmd.CloudaccountID, "cloudaccount_id", cloudaccountID, `Cloudaccount ID`)
	var leaseID int
	cc.Flags().IntVar(&cmd.LeaseID, "lease_id", leaseID, `Lease ID`)
	var expiresAt string
	cc.Flags().StringVar(&cmd.ExpiresAt, "expires_at", expiresAt, `Target expiry datetime`)
}

// Run makes the HTTP request corresponding to the ShowLeasesCommand command.
func (cmd *ShowLeasesCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/cloudaccounts/%v/leases/%v", cmd.AccountID, cmd.CloudaccountID, cmd.LeaseID)
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ShowLeases(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ShowLeasesCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
	var cloudaccountID int
	cc.Flags().IntVar(&cmd.CloudaccountID, "cloudaccount_id", cloudaccountID, `Cloudaccount ID`)
	var leaseID int
	cc.Flags().IntVar(&cmd.LeaseID, "lease_id", leaseID, `Lease ID`)
}

// Run makes the HTTP request corresponding to the TerminateLeasesCommand command.
func (cmd *TerminateLeasesCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/cloudaccounts/%v/leases/%v/terminate", cmd.AccountID, cmd.CloudaccountID, cmd.LeaseID)
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.TerminateLeases(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *TerminateLeasesCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
	var cloudaccountID int
	cc.Flags().IntVar(&cmd.CloudaccountID, "cloudaccount_id", cloudaccountID, `Cloudaccount ID`)
	var leaseID int
	cc.Flags().IntVar(&cmd.LeaseID, "lease_id", leaseID, `Lease ID`)
}

// Run makes the HTTP request corresponding to the OrderInstancesReportReportCommand command.
func (cmd *OrderInstancesReportReportCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/cloudaccounts/%v/reports/instances", cmd.AccountID, cmd.CloudaccountID)
	}
	var payload client.OrderInstancesReportReportPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.OrderInstancesReportReport(ctx, path, &payload)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *OrderInstancesReportReportCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
	var cloudaccountID int
	cc.Flags().IntVar(&cmd.CloudaccountID, "cloudaccount_id", cloudaccountID, `Cloudaccount ID`)
}

// Run makes the HTTP request corresponding to the ShowReportReportCommand command.
func (cmd *ShowReportReportCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/accounts/%v/cloudaccounts/%v/reports/generated/%v", cmd.AccountID, cmd.CloudaccountID, cmd.ReportUUID)
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ShowReportReport(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ShowReportReportCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var accountID int
	cc.Flags().IntVar(&cmd.AccountID, "account_id", accountID, `Account ID`)
	var cloudaccountID int
	cc.Flags().IntVar(&cmd.CloudaccountID, "cloudaccount_id", cloudaccountID, `Cloudaccount ID`)
	var reportUUID string
	cc.Flags().StringVar(&cmd.ReportUUID, "report_uuid", reportUUID, `Report UUID`)
}

// Run makes the HTTP request corresponding to the ShowRootCommand command.
func (cmd *ShowRootCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/"
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ShowRoot(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ShowRootCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
}
